---
exclude: ['Rakefile.rb', 'Readme.md', 'psds']
paginate: 5
markdown: rdiscount
permalink: pretty
pygments: true
projects:
    - name: "Opt-6 Products, LLC"
      logo: "opt-6.png"
      site: "http://opt-6.com/"
      description: "Opt-6 Products is a small software company that I founded in February of 2009. It specializes in Mac and iOS development, with two excellent iOS apps and one small Mac utility currently available. I am the lead developer at Opt-6, though I work with three other excellent developers: <a href=\"http://georgews.com/\">George Woodliff-Stanley</a>, <a href=\"http://twitter.com/mathcolo\">Preston M.</a>, and <a href=\"http://gnomepi.com/\">Zach Fisher</a>. I also work with one particularly talented graphic designer, <a href=\"http://wilnichols.com/\">Wil Nichols</a>."
    - name: "CZKit"
      logo: "czkit.png"
      site: "http://github.com/CarterA/CZKit"
      description: "CZKit is a collection of open-source libraries of Objective-C code, written entirely by myself. It includes a library of categories that extend existing Apple classes, a library of utility classes for random functions, a library of custom UI elements, and a library of custom views. It also includes a set of Xcode project/file templates."
    - name: "Five Square"
      logo: "fiveSquare.png"
      site: "http://fivesquareapp.com/"
      description: "Five Square is a completely new solitaire card game of strategy and skill. It combines the simplicity and elegance of a classic solitaire game with the challenge of complex strategic play. I assisted <a href=\"http://georgews.com/\">George Woodliff-Stanley</a> in the development of Five Square, while the lovely graphics were created by <a href=\"http://wilnichols.com/\">Wil Nichols</a>."
